    
#counts number of spikes generated by constant input

#here, vary n
#in mymosinit, vary stepsize, maybe dur,delay,tstop
import numpy as np
n=8 #number of steps

ncc=7 #5 pyr plus 1 olm plus 1 b cell compartments injected
if __name__ == "__main__":
    import numpy as np
    import os
    import sys

    if os.path.exists("recfolder/FI.npy"):
        os.remove("recfolder/FI.npy")
    
    Data=np.ones((ncc,n))*(-3)
    np.save("recfolder/FI",Data)
    for j in range(ncc): 
        for i in range(n):
            commandstring="python2 my_mosinit.py "+str(i)+" "+str(j)
            print(commandstring)
            os.system(commandstring)







