#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/maximilian/anaconda2/lib/python2.7/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/maximilian/anaconda2/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/maximilian/Desktop/work/neymotin/139421-master/x86_64/.libs/libnrnmech.so" "$@"
